"""initial

Revision ID: e576dca55abe
Revises: 
Create Date: 2026-03-17 15:38:39.077315

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'e576dca55abe'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('proxy_configs',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('scheme', sa.String(length=16), nullable=False),
    sa.Column('host', sa.String(length=256), nullable=False),
    sa.Column('port', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=128), nullable=True),
    sa.Column('password', sa.String(length=256), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('max_concurrent_tasks', sa.Integer(), nullable=False),
    sa.Column('cooldown_until', sa.DateTime(timezone=True), nullable=True),
    sa.Column('fail_count', sa.Integer(), nullable=False),
    sa.Column('success_count', sa.Integer(), nullable=False),
    sa.Column('captcha_count', sa.Integer(), nullable=False),
    sa.Column('timeout_count', sa.Integer(), nullable=False),
    sa.Column('last_error', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('parse_tasks',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('task_type', sa.String(length=32), nullable=False),
    sa.Column('source_value', sa.String(length=256), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('attempt_count', sa.Integer(), nullable=False),
    sa.Column('assigned_proxy_id', sa.BigInteger(), nullable=True),
    sa.Column('worker_name', sa.String(length=128), nullable=True),
    sa.Column('checkpoint_step', sa.String(length=64), nullable=True),
    sa.Column('checkpoint_data', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('last_error', sa.Text(), nullable=True),
    sa.Column('last_error_type', sa.String(length=32), nullable=True),
    sa.Column('next_retry_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_heartbeat_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('locked_by', sa.String(length=128), nullable=True),
    sa.Column('lock_expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['assigned_proxy_id'], ['proxy_configs.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('task_type', 'source_value', name='uq_parse_tasks_type_value')
    )
    op.create_index('ix_parse_tasks_assigned_proxy_id', 'parse_tasks', ['assigned_proxy_id'], unique=False)
    op.create_index('ix_parse_tasks_lock_expires_at', 'parse_tasks', ['lock_expires_at'], unique=False)
    op.create_index('ix_parse_tasks_next_retry_at', 'parse_tasks', ['next_retry_at'], unique=False)
    op.create_index('ix_parse_tasks_status', 'parse_tasks', ['status'], unique=False)
    op.create_index('ix_parse_tasks_task_type', 'parse_tasks', ['task_type'], unique=False)
    op.create_table('fedresurs_results',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('task_id', sa.BigInteger(), nullable=False),
    sa.Column('inn', sa.String(length=12), nullable=False),
    sa.Column('case_number', sa.String(length=256), nullable=False),
    sa.Column('last_publication_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('parsed_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['task_id'], ['parse_tasks.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('inn', 'case_number', 'last_publication_date', name='uq_fedresurs_results_inn_case_date')
    )
    op.create_table('kad_arbitr_results',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('task_id', sa.BigInteger(), nullable=False),
    sa.Column('case_number', sa.String(length=256), nullable=False),
    sa.Column('document_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('document_title', sa.Text(), nullable=True),
    sa.Column('document_name', sa.Text(), nullable=True),
    sa.Column('parsed_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['task_id'], ['parse_tasks.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('case_number', 'document_date', 'document_name', name='uq_kad_arbitr_results_case_date_doc')
    )
    op.create_table('task_events',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('task_id', sa.BigInteger(), nullable=False),
    sa.Column('event_type', sa.String(length=64), nullable=False),
    sa.Column('message', sa.Text(), nullable=True),
    sa.Column('payload', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['task_id'], ['parse_tasks.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_task_events_task_id', 'task_events', ['task_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_task_events_task_id', table_name='task_events')
    op.drop_table('task_events')
    op.drop_table('kad_arbitr_results')
    op.drop_table('fedresurs_results')
    op.drop_index('ix_parse_tasks_task_type', table_name='parse_tasks')
    op.drop_index('ix_parse_tasks_status', table_name='parse_tasks')
    op.drop_index('ix_parse_tasks_next_retry_at', table_name='parse_tasks')
    op.drop_index('ix_parse_tasks_lock_expires_at', table_name='parse_tasks')
    op.drop_index('ix_parse_tasks_assigned_proxy_id', table_name='parse_tasks')
    op.drop_table('parse_tasks')
    op.drop_table('proxy_configs')
    # ### end Alembic commands ###
